/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon May  8 01:20:20 2017. */

#ifndef PB_CORE_MESSAGES_CORE_PB_H_INCLUDED
#define PB_CORE_MESSAGES_CORE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _core_messages_HecateWrapper {
    uint64_t timestamp;
    pb_callback_t message;
/* @@protoc_insertion_point(struct:core_messages_HecateWrapper) */
} core_messages_HecateWrapper;

/* Default values for struct fields */

/* Initializer values for message structs */
#define core_messages_HecateWrapper_init_default {0, {{NULL}, NULL}}
#define core_messages_HecateWrapper_init_zero    {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define core_messages_HecateWrapper_timestamp_tag 1
#define core_messages_HecateWrapper_message_tag  2

/* Struct field encoding specification for nanopb */
extern const pb_field_t core_messages_HecateWrapper_fields[3];

/* Maximum encoded size of messages (where known) */
/* core_messages_HecateWrapper_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CORE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
